### ISSUE TITLE
LLL breaks modded dungeon generation

### ISSUE THREAD

**Issue by Void866** [IAmBatby/LethalLevelLoader#39]
So if you have any sort of modded interior (LCoffice, Scoops variety mod, MoreInteriors) and then land on a modded moon run by LLL, all of the modded interiors will have their spawn weight set to 0, making it impossible for them to spawn. This occurs on LLL version 1.10 and onwards. 
Version 1.07 works perfectly fine and all the interiors can spawn. I believe it's because of the config added to LLL in 1.10. Can we have a way to just disable the config settings as it causes some major problems with other mods. (I've had issues with scrap and monsters spawns since 1.10 while using Advanced Company but it seems ive sorted that)

**Comment by Uniteria** [comment]
Thats a good call mate. We have to wait for LLL to be viable on version 1.10 and above. Sticking to 1.0.7 for now.

**Comment by Mr-Twave** [comment]
Right. While I love what the author's done with the terminal rework and the mod itself, the dungeon stuff the author did with this mod needed a little testing before it rolled out; it would have been great just to push out the new version with the terminal overhaul only since no other mod and just lethal level loader performed this.

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
