### ISSUE TITLE
it spawned different dungeons on the same planet

### ISSUE THREAD

**Issue by apeng0907** [IAmBatby/LethalLevelLoader#55]
**i have six friends playing together in the same room.But it spawned different dungeons on the same planet**
**This situation has been encountered many times, and this is the log of one of the interceptions.**

### Most of us have entered Minecraft Stronghold：
[Info   :LethalLevelLoader] Level: 61 March Contains DungeonFlow: Level1Flow3Exits In DungeonGenerator That Was Not Found In RoundManager, Adding!
[Info   :LethalLevelLoader] Re-Adjusting DungeonFlowTypes Array For Late Arriving Vanilla DungeonFlow
[Info   :LethalPosters] Patching GenerateNewLevelClientRpc in RoundManager
[Info   :LethalPosters] Patching the textures
[Info   :LethalPosters] Patching Posters (Instance) with G:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\Nazarick-Nazarick_posters\LethalPosters\posters\1.png
[Info   :LethalPosters] Patching TipsPoster (Instance) with G:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\Nazarick-Nazarick_posters\LethalPosters\tips\1.jpg
[Info   :LethalLevelLoader] Setting Random DungeonFlows!
[Warning:LethalLevelLoader] Disabling LethalLib Dungeon.RoundManager_GenerateNewFloor() Function To Prevent Conflicts
[Info   :ImoutoSama.ScarletMansion] Disabling SDM logic
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :LethalLevelLoader] Fire Exit Patch Report, Details Below;

EntranceTeleport's Found, March Contains 4 Entrances! ( 3 Fire Escapes) 
Main Entrance: EntranceTeleportA (Entrance ID: 0) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportB (Entrance ID: 1) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportC (Entrance ID: 2) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportD (Entrance ID: 3) (Dungeon ID: 5)
Found Fire Escape GlobalProp: (ID: 1231), Modifying Spawnrate Count From (1,1) To (3,3)

[Info   :LethalLevelLoader] Created New Day History Log! PlanetName: March , DungeonName: Minecraft Stronghold , Quota: 0 , Day: 2 , Weather: None
[Info   :LethalLevelLoader] PreProcessing
[Info   :LethalLevelLoader] MainPath

### One of us entered the ScarletMansion
[Info   :LethalLevelLoader] Level: 61 March Contains DungeonFlow: Level1Flow3Exits In DungeonGenerator That Was Not Found In RoundManager, Adding!
[Info   :LethalLevelLoader] Re-Adjusting DungeonFlowTypes Array For Late Arriving Vanilla DungeonFlow
[Info   :LethalPosters] Patching GenerateNewLevelClientRpc in RoundManager
[Info   :LethalPosters] Patching the textures
[Info   :LethalPosters] Patching Posters (Instance) with D:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\Nazarick-Nazarick_posters\LethalPosters\posters\1.png
[Info   :LethalPosters] Patching TipsPoster (Instance) with D:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\Nazarick-Nazarick_posters\LethalPosters\tips\1.jpg
[Info   :LethalLevelLoader] Setting Random DungeonFlows!
[Warning:LethalLevelLoader] Disabling LethalLib Dungeon.RoundManager_GenerateNewFloor() Function To Prevent Conflicts
[Info   :ImoutoSama.ScarletMansion] Disabling SDM logic
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :ImoutoSama.ScarletMansion] Loading Scarlet Mansion map so we are activating the alt. dungen scripts
[Info   :ImoutoSama.ScarletMansion] Set new dungeon bounds with, (0.00, 4.00, 58.67) and (240.00, 40.00, 133.33)
[Info   :ImoutoSama.ScarletMansion] Length of main path be: (12 - 15)
[Info   :ImoutoSama.ScarletMansion] Loaded custom enemies and items for Level4March
[Info   :ImoutoSama.ScarletMansion] Added Crawler:4 to bedroom event
[Info   :ImoutoSama.ScarletMansion] Added Jester:7 to bedroom event
[Info   :ImoutoSama.ScarletMansion] Added Nutcracker:8 to bedroom event
[Info   :ImoutoSama.ScarletMansion] Added SpringMan:18 to bedroom event
[Info   :ImoutoSama.ScarletMansion] Added Knight:19 to bedroom event
[Info   :LethalLevelLoader] Fire Exit Patch Report, Details Below;

EntranceTeleport's Found, March Contains 4 Entrances! ( 3 Fire Escapes) 
Main Entrance: EntranceTeleportA (Entrance ID: 0) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportB (Entrance ID: 1) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportC (Entrance ID: 2) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportD (Entrance ID: 3) (Dungeon ID: 5)
Found Fire Escape GlobalProp: (ID: 1231), Modifying Spawnrate Count From (1,1) To (3,3)

[Info   :LethalLevelLoader] Created New Day History Log! PlanetName: March , DungeonName: Scarlet Devil Mansion , Quota: 2 , Day: 9 , Weather: None
[Info   :LethalLevelLoader] PreProcessing
[Info   :LethalLevelLoader] MainPath

**Comment by apeng0907** [comment]
I don't know what caused it, but the friend who entered the wrong dungeon has an additional shortcut bar on the right side of the screen

**Comment by apeng0907** [comment]
[LogOutput(4).log](https://github.com/IAmBatby/LethalLevelLoader/files/14437070/LogOutput.4.log)

**Comment by apeng0907** [comment]
This is the log that entered the map incorrectly

**Comment by apeng0907** [comment]
Could you please help resolve this error

**Comment by ilandedatsamsoononthe19thofmay1919** [comment]
We're playing with Exploration pack and we get a similar bug. Those who fall off the map get a different information about a completely different planet on the ship monitor after setting the destination.

Example: Host typed Maritopia. host sees Maritopia. I see SCP Lab. Another friend sees Atlas Abyss. When the ship lands, the relevant moon's dungeon is generated. Since it's different for each player, everybody but the player who sees the right planet on monitor usually falls into the void or gets another dungeon. 

Here are the mods we use : 

fumiko-CullFactory-0.9.0
Tolian-Maritopia-0.3.5
mrov-TerminalFormatter-0.0.7
Piggy-LC_Office-1.0.21
HolographicWings-LethalExpansion-1.3.44
Tolian-Celestria-0.4.7
Hardy-LCMaxSoundsFix-1.1.0
AudioKnight-StarlancerAIFix-3.2.0
Magic_Wesley-Infernis-3.1.0
KayNetsua-E_Gypt_Moon-2.0.15
Major_And_Skiz-MoreInteriors-2.5.0
xilophor-LethalNetworkAPI-2.1.6
sfDesat-ViewExtension-1.1.0
scoopy-Scoopys_Variety_Mod-1.2.0
sfDesat-ExpansionAssets-1.1.0
sfDesat-Orion-1.3.0
sfDesat-Aquatis-1.1.1
Evaisa-LethalLib-0.14.2
Badham_Mods-SCPFoundationDungeon-3.0.0
AudioKnight-StarlancerMoons-0.5.7
Zingar-Atlas_Abyss-1.1.8
Zingar-SecretLabs-3.3.7
jockie-LethalExpansionCore-1.3.15
sfDesat-Celest-0.2.1
Lordfirespeed-OdinSerializer-2022.11.9
Ceelery-Kast-1.0.3
Evaisa-HookGenPatcher-0.0.5
BepInEx-BepInExPack-5.4.2100
Evaisa-LethalThings-0.9.4
EliteMasterEric-Coroner-1.6.0
Ozone-Runtime_Netcode_Patcher-0.2.5
Sligili-More_Emotes-1.3.3
x753-Mimics-2.4.1
TwinDimensionalProductions-CoilHeadStare-1.0.9
TheFluff-FairAI-1.3.3
RickArg-Helmet_Cameras-2.1.5
FutureSavior-Hold_Scan_Button-1.1.1
anormaltwig-LateCompany-1.0.11
FlipMods-LetMeLookDown-1.0.1
FlipMods-MoreBlood-1.0.2
notnotnotswipez-MoreCompany-1.8.1
egeadam-MoreScreams-1.0.3
x753-More_Suits-1.4.1
RugbugRedfern-Skinwalkers-4.0.1
Blorb-WeatherMultipliers-1.1.0
malco-Lategame_Upgrades-3.3.0
Rune580-LethalCompany_InputUtils-0.6.3
KlutzyBubbles-InfiniteEmote-1.3.3
sfDesat-Explorations-2.2.3
IAmBatby-LethalLevelLoader-1.1.5 (same happens on 1.1.6 version we tried reverting it just in case)


Here are the logs of 3 distinct situations where this happened to us in. (all were with the 1.1.6 version if i remember correctly.)

![resim](https://github.com/IAmBatby/LethalLevelLoader/assets/117932792/dc16d3d8-9e3c-4d54-9368-709ef8ed1a96)


[LogOutput(3).log](https://github.com/IAmBatby/LethalLevelLoader/files/14453814/LogOutput.3.log)
[LogOutput(2).log](https://github.com/IAmBatby/LethalLevelLoader/files/14453815/LogOutput.2.log)
[LogOutput(1).log](https://github.com/IAmBatby/LethalLevelLoader/files/14453816/LogOutput.1.log)

**Comment by ilandedatsamsoononthe19thofmay1919** [comment]
version 1.1.5 is the same but 1.1.4 works fine.

**Comment by ilandedatsamsoononthe19thofmay1919** [comment]
> > > version 1.1.5 is the same but 1.1.4 works fine.
> > 
> > 
> > Wait so if i play on 1.1.4 the falling throught the void glitch stops?
> 
> After testing, the old version (1.1.4) fixes falling into the Void and different dungeons, but some dungeons that rely on the new version of LLL don't seem to load

reverting does not fix anything it just makes it less probable, i forgot to edit. there is another mod called lethal level loader fixed by refract. use that one instead.

**Comment by rainbow137** [comment]
> > > > version 1.1.5 is the same but 1.1.4 works fine.
> > > 
> > > 
> > > Wait so if i play on 1.1.4 the falling throught the void glitch stops?
> > 
> > 
> > After testing, the old version (1.1.4) fixes falling into the Void and different dungeons, but some dungeons that rely on the new version of LLL don't seem to load
> 
> reverting does not fix anything it just makes it less probable, i forgot to edit. there is another mod called lethal level loader fixed by refract. use that one instead.
> 
> these glitches happen because LLL constantly changes the config and you get a total mess. just compare it with your friends' and you'll see.

After playing with my friends, this fix mod "LethalLevelLoaderFixed" still doesn't seem to fix these problems in the dungeon, in essence, it still happens probably, which has bothered me for a long time, I hope LLL will be updated soon

https://thunderstore.io/c/lethal-company/p/Refract/LethalLevelLoaderFixed/

**Comment by Qugar** [comment]
Are you sorting the moons? I had the same problem but as soon as no sorting was selected in the config everything worked again.

**Comment by 1753449579** [comment]
There are duplicate dungeons in the <LethalLevelLoader.cfg>。I deleted the file and let it regenerate

**Comment by RatserX** [comment]
Had the same problem. Removing ScarletDevilMansion, along with all of its dependencies, fixed the issue. It seems LLL may have some issues with mods that modify the dungeon generation. I remember a long time ago I had some issues with the Scoopys Variety Mod too. Right now the only issue I have is that sometimes the weather is desynced, but I think WeatherTweaks can be used to fix that.

**Comment by RatserX** [comment]
> After playing with my friends, this fix mod "LethalLevelLoaderFixed" still doesn't seem to fix these problems in the dungeon, in essence, it still happens probably, which has bothered me for a long time, I hope LLL will be updated soon
> 
> https://thunderstore.io/c/lethal-company/p/Refract/LethalLevelLoaderFixed/

I just gave up playing on LLL custom moons until LLL gets updated, the overall experience is just too unstable.

Some things to note:
- Installing LC API helps to sync the weather, but it isn't a consistent fix.
- Installing LethalLevelLoaderFixed helps to sync the dungeons, sometimes people can't enter them (LLLF is failing to map a correct exit, maybe?).
- Changing the settings of LethalLevelLoader didn't help at all.

**Comment by ilandedatsamsoononthe19thofmay1919** [comment]
is it still not fixed? lmao. lazy dev.

> > After playing with my friends, this fix mod "LethalLevelLoaderFixed" still doesn't seem to fix these problems in the dungeon, in essence, it still happens probably, which has bothered me for a long time, I hope LLL will be updated soon
> > https://thunderstore.io/c/lethal-company/p/Refract/LethalLevelLoaderFixed/
> 
> I just gave up playing on LLL custom moons until LLL gets updated, the overall experience is just too unstable.
> 
> Some things to note:
> 
>     * Installing LC API helps to sync the weather, but it isn't a consistent fix.
> 
>     * Installing LethalLevelLoaderFixed helps to sync the dungeons, but sometimes people can't enter them (LLLF is failing to map a correct exit, maybe?).
> 
>     * Changing the settings of LethalLevelLoader didn't help at all.

**Comment by IAmBatby** [comment]
Resolved in future versions of the project.
