### ISSUE TITLE
The scrap value setting didn't work well.

### ISSUE THREAD

**Issue by meBVH** [IAmBatby/LethalLevelLoader#82]
I set "Enable Content Configuration = true",but the Scrap Settings such that Minimum/Maximum Total Scrap Value didn't work right.
I set Maximum Total Scrap Value to 150, but it still had 400+ value scrap in game.
And I tried to use this mod in separate, but it still didn't work.

**Comment by WhiteSpike** [comment]
The problem with this issue is that the game itself doesn't use these variables (minTotalScrapValue and maxTotalScrapValue) when generating scrap in the moon (even though they are stored in the objects associated to each level which is then configurable through LLL).

To make these configurations actually take effect, there would have to be some sort of patch in the spawn scrap code in which it would make them be affected by these values without breaking anything.

**Comment by IAmBatby** [comment]
In addition to what WhiteSpike has said, While those values are currently of no use I have added them as configuration options in the event future versions of the game start using them. Currently I do not intend on making them work as I think that gameplay change is out of scope for an API mod like this.
