### ISSUE TITLE
Terminal conflict with the term "rock"

### ISSUE THREAD

**Issue by Decryptu** [IAmBatby/LethalLevelLoader#86]
Hello, there is a conflict between this mod "filter rocky", and the "rocket launcher" from [LethalThings](https://thunderstore.io/c/lethal-company/p/Evaisa/LethalThings/)

If you write "rocket" or "rocket launcher" in the terminal, it will select `filterRockyNode` : 

```log
[Info   : Unity Log] secondary use A
[Info   : Unity Log] Parsed word: rocket
[Info   : Unity Log] Could not parse word: launcher
[Info   : Unity Log] noun keyword: rocky ; verb keyword: filter ; result null? : False
[Info   : Unity Log] result: filterRockyNode
```

Thank you :)

**Comment by WhiteSpike** [comment]
That's really a vanilla problem due to it not being able to distinguish terminal nodes with similar verbs/nouns.
There are mods that resolve that issue such as [TerminalConflictFix](https://thunderstore.io/c/lethal-company/p/SylviBlossom/TerminalConflictFix/) so maybe you can try that and see if it still persists.
