### ISSUE TITLE
Is there an actual tutorial for this?

### ISSUE THREAD

**Issue by ThatonePanMan** [IAmBatby/LethalLevelLoader#98]
Like the title says, is there a full tutorial for setting up the v50 version or any tutorial that can be applicable to the v50 version beyond just
- "Download unity"
- "download this example project from another person that isn't directly related to LLL"
- "good luck"

**Comment by IAmBatby** [comment]
Unfortunately due to IRL circumstances I am unable to spend time documentation development of custom content using LethalLevelLoader. In the meantime I would suggest looking at resources such as Audio Knight's YouTube tutorial on creating a custom moon or some of the various resources found in the Lethal Company modding Discord. I would love to provide official documentation for the project in the future if circumstances change.
